// <auto-generated />
using System;
using ApiRapunzel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiRapunzel.Migrations
{
    [DbContext(typeof(ContextoApi))]
    [Migration("20190928223226_foreignKey_Citas")]
    partial class foreignKey_Citas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiRapunzel.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EstadoCitaIdEstadoCita");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Hora");

                    b.Property<int>("IdCliente");

                    b.Property<int>("IdEstilista");

                    b.HasKey("IdCita");

                    b.HasIndex("EstadoCitaIdEstadoCita");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstilista");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("ApiRapunzel.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<int>("Documento");

                    b.Property<string>("Nombre");

                    b.Property<string>("Usuario");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ApiRapunzel.Models.EstadoCita", b =>
                {
                    b.Property<int>("IdEstadoCita")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("IdEstadoCita");

                    b.ToTable("EstadoCitas");
                });

            modelBuilder.Entity("ApiRapunzel.Models.Estilista", b =>
                {
                    b.Property<int>("IdEstilista")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos");

                    b.Property<string>("Nombre");

                    b.HasKey("IdEstilista");

                    b.ToTable("Estilistas");
                });

            modelBuilder.Entity("ApiRapunzel.Models.Cita", b =>
                {
                    b.HasOne("ApiRapunzel.Models.EstadoCita")
                        .WithMany("IdCita")
                        .HasForeignKey("EstadoCitaIdEstadoCita");

                    b.HasOne("ApiRapunzel.Models.Cliente")
                        .WithMany("IdCita")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ApiRapunzel.Models.Estilista")
                        .WithMany("IdCita")
                        .HasForeignKey("IdEstilista")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
